DEEPSORT:
  MODEL_PATH: "model/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 1.0
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 30
  N_INIT: 3
  NN_BUDGET: 100

FEATURE_EXTRACTOR:
  MODEL: "osnet_x1_0"
  DEVICE: "cuda"
  FP16: False

TRACKING:
  METRIC_TYPE: "cosine"
  CONF_THRESHOLD: 0.5
  IOU_THRESHOLD: 0.3
